# Generated by Django 4.0.1 on 2022-03-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_call'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='name',
            new_name='names',
        ),
    ]
